project:
  type: book
  output-dir: docs

book:
  title: "Descriptive Statistics"
  author: "Thiyanga S. Talagala"
  date: "6/3/2025"
  chapters:
    - index.qmd
    - t1.qmd
    - t2.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

